/**
 * Reusable PDF Header with Kambaa Logo
 * This utility provides a consistent header for ALL PDF reports
 */

const fs = require("fs");
const path = require("path");

// Logo path - stored in backend root directory
const LOGO_PATH = path.join(__dirname, "..", "kambaa-logo.png");

/**
 * Add company header with logo to PDF document
 * @param {PDFDocument} doc - PDFKit document instance
 * @param {string} reportTitle - Title of the report (e.g., "PETTY CASH EXPENSE REPORT")
 * @param {Object} options - Optional configuration
 * @param {number} options.logoWidth - Logo width (default: 70)
 * @param {number} options.logoHeight - Logo height (default: 70)
 * @param {number} options.startY - Y position to start (default: 30)
 * @returns {number} - Y position after header (for content to start)
 */
const addPDFHeader = (doc, reportTitle, options = {}) => {
  const { logoWidth = 70, logoHeight = 70, startY = 30 } = options;

  const logoX = 40;
  const textX = logoX + logoWidth + 20; // Position text to the right of logo

  console.log("📄 PDF Header - Logo path:", LOGO_PATH);
  console.log("📄 PDF Header - Logo exists:", fs.existsSync(LOGO_PATH));

  try {
    if (fs.existsSync(LOGO_PATH)) {
      // Add logo on the left side
      doc.image(LOGO_PATH, logoX, startY, {
        width: logoWidth,
        height: logoHeight,
        fit: [logoWidth, logoHeight],
        align: "center",
        valign: "center",
      });

      // Company name and tagline beside logo (horizontally aligned)
      doc
        .fontSize(22)
        .fillColor("#023e8a")
        .text("Kambaa Inc.", textX, startY + 10, {
          align: "left",
          continued: false,
        });

      doc
        .fontSize(10)
        .fillColor("#666666")
        .text("Petty Cash Management System", textX, startY + 38, {
          align: "left",
        });

      console.log("✅ PDF Header - Logo loaded successfully");
    } else {
      console.log("⚠️ PDF Header - Logo not found, using text-only header");
      // Fallback: centered text without logo
      doc.fontSize(22).fillColor("#023e8a").text("Kambaa Inc.", logoX, startY, {
        align: "center",
        width: 515,
      });

      doc
        .fontSize(10)
        .fillColor("#666666")
        .text("Petty Cash Management System", logoX, startY + 28, {
          align: "center",
          width: 515,
        });
    }
  } catch (error) {
    console.error("❌ PDF Header - Error loading logo:", error.message);
    // Fallback on error
    doc.fontSize(22).fillColor("#023e8a").text("Kambaa Inc.", logoX, startY, {
      align: "center",
      width: 515,
    });

    doc
      .fontSize(10)
      .fillColor("#666666")
      .text("Petty Cash Management System", logoX, startY + 28, {
        align: "center",
        width: 515,
      });
  }

  // Add Report Title
  const titleY = startY + logoHeight + 15;
  doc
    .fontSize(16)
    .fillColor("#023e8a")
    .text(reportTitle, 40, titleY, { align: "center", width: 515 });

  // Return Y position for content to start after header
  return titleY + 30;
};

/**
 * Add page header for subsequent pages (smaller version)
 * @param {PDFDocument} doc - PDFKit document instance
 * @returns {number} - Y position after header
 */
const addPageHeader = (doc) => {
  const startY = 20;
  const logoWidth = 40;

  try {
    if (fs.existsSync(LOGO_PATH)) {
      doc.image(LOGO_PATH, 40, startY, { width: logoWidth, height: 40 });
      doc
        .fontSize(12)
        .fillColor("#023e8a")
        .text("Kambaa Inc.", 90, startY + 10, { align: "left" });
    } else {
      doc
        .fontSize(12)
        .fillColor("#023e8a")
        .text("Kambaa Inc.", 40, startY + 10, { align: "left" });
    }
  } catch (error) {
    doc
      .fontSize(12)
      .fillColor("#023e8a")
      .text("Kambaa Inc.", 40, startY + 10, { align: "left" });
  }

  return 70; // Return Y position for content
};

/**
 * Add PDF footer with page numbers and confidentiality notice
 * @param {PDFDocument} doc - PDFKit document instance
 * @param {string} generatedBy - Name of user who generated the report
 */
const addPDFFooter = (doc, generatedBy = "System") => {
  const footerY = 750;

  doc
    .fontSize(8)
    .fillColor("#666666")
    .text("---", 40, footerY, { align: "center", width: 515 })
    .text(
      "This is a system-generated report from Kambaa Petty Cash Management System",
      40,
      footerY + 12,
      { align: "center", width: 515 },
    )
    .text(
      `Generated by: ${generatedBy} | Date: ${new Date().toLocaleDateString("en-IN")}, ${new Date().toLocaleTimeString("en-IN")}`,
      40,
      footerY + 24,
      { align: "center", width: 515 },
    )
    .text("Confidential - For Internal Use Only", 40, footerY + 36, {
      align: "center",
      width: 515,
    });
};

/**
 * Get the logo path for external use
 * @returns {string} - Absolute path to logo file
 */
const getLogoPath = () => LOGO_PATH;

/**
 * Check if logo exists
 * @returns {boolean} - True if logo file exists
 */
const logoExists = () => fs.existsSync(LOGO_PATH);

module.exports = {
  addPDFHeader,
  addPageHeader,
  addPDFFooter,
  getLogoPath,
  logoExists,
  LOGO_PATH,
};
